import { FAQItem, SupportedLanguage } from './types';

export const FAQ_ITEMS: FAQItem[] = [
  // 1. ABOUT HARSHA
  {
    id: 'about',
    category: 'about',
    answer: {
      en: 'Harsha is a freelance software developer specializing in full-stack web applications, AI workflow automation, and computer vision systems. Guided by the core principle: "Big dreams shouldn\'t have to wait for big budgets," Harsha crafts thoughtful, high-performance digital solutions for clients worldwide.',
      ta: 'ஹர்ஷா ஒரு ஃப்ரீலான்ஸ் மென்பொருள் உருவாக்குநர் (Freelance Software Developer). அவர் ஃபுல்-ஸ்டாக் வலைத்தளங்கள், AI ஆட்டோமேஷன் மற்றும் கணினி பார்வை (Computer Vision) அமைப்புகளில் நிபுணத்துவம் பெற்றவர். “பெரிய கனவுகளுக்கு பெரிய பட்ஜெட் தேவையில்லை” என்ற கொள்கையுடன் தரமான மென்பொருள்களை உருவாக்குகிறார்.',
      hi: 'हर्षा एक फ्रीलांस सॉफ्टवेयर डेवलपर हैं जो फुल-स्टैक वेब डेवलपमेंट, AI वर्कफ़्लो ऑटोमेशन और कंप्यूटर विज़न सिस्टम में विशेषज्ञता रखते हैं। उनका मुख्य सिद्धांत है: "बड़े सपनों के लिए बड़े बजट की ज़रूरत नहीं होती।" वे ग्राहकों के लिए आधुनिक और स्केलेबल डिजिटल समाधान तैयार करते हैं।',
      ml: 'ഫുൾ-സ്റ്റാക്ക് വെബ് ആപ്ലിക്കേഷനുകൾ, AI വർക്ക്‌ഫ്ലോ ഓട്ടോമേഷൻ, കമ്പ്യൂട്ടർ വിഷൻ സിസ്റ്റങ്ങൾ എന്നിവയിൽ വിദഗ്ദ്ധനായ ഒരു ഫ്രീലാൻസ് സോഫ്റ്റ്‌വെയർ ഡെവലപ്പറാണ് ഹർഷ. "വലിയ സ്വപ്നങ്ങൾക്ക് വലിയ ബജറ്റ് ആവശ്യമില്ല" എന്ന ലക്ഷ്യത്തോടെ മികച്ച ഡിജിറ്റൽ പരിഹാരങ്ങൾ അദ്ദേഹം നൽകുന്നു.',
    },
    keywords: {
      en: [
        'who are you',
        'about harsha',
        'who is harsha',
        'tell me about yourself',
        'about you',
        'background',
        'bio',
        'profile',
        'experience',
        'developer',
        'freelancer',
      ],
      ta: [
        'நீங்கள் யார்',
        'ஹர்ஷா பற்றி',
        'உங்களைப் பற்றி',
        'சுயவிவரம்',
        'அனுபவம்',
        'ஹர்ஷா யார்',
        'யார் நீங்கள்',
        'விவரம்',
      ],
      hi: [
        'आप कौन हैं',
        'हर्षा के बारे में',
        'अपने बारे में बताएं',
        'परिचय',
        'अनुभव',
        'हर्षा कौन हैं',
        'बायो',
      ],
      ml: [
        'ആരാണ് നിങ്ങൾ',
        'ഹർഷയെക്കുറിച്ച്',
        'നിങ്ങളെക്കുറിച്ച് പറയൂ',
        'പരിചയം',
        'ഹർഷ ആരാണ്',
        'വിവരണം',
      ],
    },
    action: {
      label: {
        en: 'Explore Services',
        ta: 'சேவைகளைப் பார்க்கவும்',
        hi: 'सेवाएं देखें',
        ml: 'സേവനങ്ങൾ കാണുക',
      },
      url: '/services',
    },
    followUps: {
      en: ['What services do you offer?', 'Tell me about your projects', 'How can I contact Harsha?'],
      ta: ['என்ன சேவைகள் வழங்குகிறீர்கள்?', 'திட்டங்கள் பற்றி சொல்லுங்கள்', 'ஹர்ஷாவை எவ்வாறு தொடர்பு கொள்வது?'],
      hi: ['आप क्या सेवाएं देते हैं?', 'अपने प्रोजेक्ट्स के बारे में बताएं', 'हर्षा से संपर्क कैसे करें?'],
      ml: ['എന്തൊക്കെ സേവനങ്ങൾ നൽകുന്നു?', 'പ്രോജക്റ്റുകളെക്കുറിച്ച് പറയൂ', 'ഹർഷയുമായി എങ്ങനെ ബന്ധപ്പെടാം?'],
    },
  },

  // 2. SERVICES
  {
    id: 'services',
    category: 'services',
    answer: {
      en: 'Harsha provides 5 core software engineering services:\n\n1. Full-Stack Web Development (Next.js, React, Node.js, Fastify, PostgreSQL)\n2. Frontend Engineering & Responsive UI (Tailwind CSS, high-contrast obsidian design)\n3. UI/UX & Interaction Design (3D animations, micro-interactions, responsive ergonomics)\n4. AI & Systems Automation (Multi-service LLM integration, webhooks, automated pipelines)\n5. Website Redesign & Bug Fixes (Performance audits, speed optimization, responsive repairs)',
      ta: 'ஹர்ஷா வழங்கும் 5 முதன்மை சேவைகள்:\n\n1. ஃபுல்-ஸ்டாக் வலைப்பயன்பாட்டு உருவாக்கம் (Next.js, React, Node.js, Fastify, PostgreSQL)\n2. முன்பக்க வடிவமைப்பு & ரெஸ்பான்சிவ் UI (Tailwind CSS, அதிநவீன வடிவமைப்பு)\n3. UI/UX & தொடர்பு வடிவமைப்பு (3D அனிமேஷன், மென்மையான இடைமுகம்)\n4. AI & ஆட்டோமேஷன் தீர்வுகள் (LLM ஒருங்கிணைப்பு, தானியங்கி பைப்லைன்கள்)\n5. வலைத்தள மறுவடிவமைப்பு & பிழை திருத்தம் (வேக மேம்பாடு, செயல்திறன் தணிக்கை)',
      hi: 'हर्षा 5 प्रमुख सेवाएं प्रदान करते हैं:\n\n1. फुल-स्टैक वेब डेवलपमेंट (Next.js, React, Node.js, Fastify, PostgreSQL)\n2. फ्रंटएंड डेवलपमेंट और रिस्पॉन्सिव यूआई (Tailwind CSS, प्रीमियम डार्क थीम)\n3. UI/UX और इंटरैक्शन डिज़ाइन (3D एनिमेशन, आधुनिक इंटरफ़ेस)\n4. AI और सिस्टम्स ऑटोमेशन (LLM इंटीग्रेशन, ऑटोमेटेड वर्कफ़्लो)\n5. वेबसाइट रीडिज़ाइन और बग फिक्सिंग (स्पीड ऑप्टिमाइज़ेशन, प्रदर्शन सुधार)',
      ml: 'ഹർഷ നൽകുന്ന 5 പ്രധാന സേവനങ്ങൾ:\n\n1. ഫുൾ-സ്റ്റാക്ക് വെബ് ഡെവലപ്‌മെന്റ് (Next.js, React, Node.js, PostgreSQL)\n2. ഫ്രണ്ട്-എൻഡ് ഡിസൈൻ & റെസ്പോൺസീവ് UI (Tailwind CSS, പ്രീമിയം ബ്ലാക്ക് ഡിസൈൻ)\n3. UI/UX & ഇന്ററാക്ഷൻ ഡിസൈൻ (3D ആനിമേഷനുകൾ, സ്മൂത്ത് യൂസർ ഇന്റർഫേസ്)\n4. AI & ഓട്ടോമേഷൻ സൊല്യൂഷൻസ് (LLM ഇന്റഗ്രേഷൻ, ഓട്ടോമേറ്റഡ് പൈപ്പ്‌ലൈനുകൾ)\n5. വെബ്‌സൈറ്റ് റീഡിസൈൻ & ബഗ് പരിഹാരം (സ്പീഡ് ഒപ്റ്റിമൈസേഷൻ, പെർഫോമൻസ് ഓഡിറ്റ്)',
    },
    keywords: {
      en: [
        'services',
        'service',
        'what do you do',
        'what can you build',
        'web development',
        'frontend',
        'backend',
        'full stack',
        'fullstack',
        'redesign',
        'bug fixing',
        'ui ux',
        'automation',
        'offerings',
      ],
      ta: [
        'சேவைகள்',
        'என்ன செய்வீர்கள்',
        'வலைத்தள உருவாக்கம்',
        'முன்பக்க வடிவமைப்பு',
        'பின்பக்க வடிவமைப்பு',
        'ஆட்டோமேஷன்',
        'பிழை திருத்தம்',
        'சேவை',
      ],
      hi: [
        'सेवाएं',
        'आप क्या करते हैं',
        'वेब डेवलपमेंट',
        'फ्रंटएंड',
        'फुल स्टैक',
        'ऑटोमेशन',
        'बग ठीक करना',
        'रीडिजाइन',
        'सर्विस',
      ],
      ml: [
        'സേവനങ്ങൾ',
        'എന്താണ് ചെയ്യുന്നത്',
        'വെബ് ഡെവലപ്‌മെന്റ്',
        'ഫ്രണ്ട് എൻഡ്',
        'ഫുൾ സ്റ്റാക്ക്',
        'ഓട്ടോമേഷൻ',
        'ബഗ്ഗ് ഫിക്സിംഗ്',
        'റീഡിസൈൻ',
      ],
    },
    action: {
      label: {
        en: 'View Full Services Page',
        ta: 'முழு சேவைகள் பக்கத்தைப் பார்க்கவும்',
        hi: 'सेवाओं का पूरा पेज देखें',
        ml: 'സേവന പേജ് കാണുക',
      },
      url: '/services',
    },
    followUps: {
      en: ['How much does a website cost?', 'Tell me about the Pipeline Robot', 'How to contact Harsha?'],
      ta: ['விலை எவ்வளவு ஆகும்?', 'பைப்லைன் ரோபோ பற்றி சொல்லுங்கள்', 'ஹர்ஷாவைத் தொடர்பு கொள்வது எப்படி?'],
      hi: ['प्रोजेक्ट की फीस कितनी है?', 'पाइपलाइन रोबोट के बारे में बताएं', 'हर्षा से संपर्क कैसे करें?'],
      ml: ['പ്രോജക്റ്റിന് എത്ര ചെലവാകും?', 'പൈപ്പ്‌ലൈൻ റോബോട്ടിനെക്കുറിച്ച് പറയൂ', 'ഹർഷയുമായി എങ്ങനെ ബന്ധപ്പെടാം?'],
    },
  },

  // 3. PIPELINE INSPECTION ROBOT
  {
    id: 'pipeline_robot',
    category: 'pipeline_robot',
    answer: {
      en: 'The Pipeline Inspection Robot is an authentic engineered prototype designed for internal cylindrical pipe traversal and non-destructive testing.\n\nKey Engineering Features:\n• Edge Computer Vision: Real-time image processing for detecting internal fractures, cracks, weld anomalies, and chemical corrosion.\n• Adaptive Drive Chassis: High-torque cylindrical mobility mechanism capable of navigating smooth and fouled pipe walls.\n• Telemetry & Diagnostics: Live video feeds and structural health telemetry dispatched to a central diagnostic dashboard.\n• Tech Stack: Built using Python, OpenCV, embedded microcontrollers, and IoT communication protocols.',
      ta: 'பைப்லைன் ஆய்வு ரோபோ (Pipeline Inspection Robot) என்பது குழாய்களுக்குள் சென்று ஆய்வு செய்யும் ஒரு பொறியியல் மாதிரியாகும்.\n\nமுக்கிய சிறப்பம்சங்கள்:\n• எட்ஜ் கம்ப்யூட்டர் விஷன் (Computer Vision): விரிசல்கள், துருப்பிடித்தல் மற்றும் உள் சேதங்களை நிகழ்நேரத்தில் துல்லியமாகக் கண்டறியும்.\n• உருளை வடிவ இயங்குதளம்: குழாயின் உள்பகுதியில் சீராக நகரும் உயர்-முறுக்குவிசை கொண்ட இயங்கு நுட்பம்.\n• நேரலை தகவல் பரிமாற்றம்: சென்சார் தகவல்களையும் நேரலை வீடியோவையும் மத்திய கட்டுப்பாட்டுத் திரைக்கு அனுப்பும்.\n• தொழில்நுட்பம்: Python, OpenCV, மைக்ரோகண்ட்ரோலர்கள் மற்றும் IoT தகவல்தொடர்பு நெறிமுறைகள் மூலம் உருவாக்கப்பட்டது.',
      hi: 'पाइपलाइन इंस्पेक्शन रोबोट (Pipeline Inspection Robot) एक वास्तविक इंजीनियरिंग प्रोटोटाइप है जो पाइपलाइनों के आंतरिक निरीक्षण के लिए बनाया गया है।\n\nमुख्य विशेषताएं:\n• एज कंप्यूटर विज़न (Computer Vision): आंतरिक दरारें, वेल्डिंग दोष और जंग को रियल-टाइम में पहचानता है।\n• बेलनाकार ड्राइव चेसिस: पाइप के अंदर आसानी से चलने में सक्षम हाई-टॉर्क मैकेनिज्म।\n• लाइव टेलीमेट्री: संरचनात्मक डेटा और वीडियो स्ट्रीम को सीधे कंट्रोल डैशबोर्ड पर भेजता है।\n• तकनीक: Python, OpenCV, एम्बेडेड माइक्रोकंट्रोलर्स और IoT प्रोटोकॉल द्वारा संचालित।',
      ml: 'പൈപ്പ്‌ലൈൻ ഇൻസ്പെക്ഷൻ റോബോട്ട് (Pipeline Inspection Robot) എന്നത് പൈപ്പുകളുടെ ഉൾവശം പരിശോധിക്കുന്നതിനായി വികസിപ്പിച്ച ഒരു എഞ്ചിനീയറിംഗ് പ്രോട്ടോടൈപ്പാണ്.\n\nപ്രധാന സവിശേഷതകൾ:\n• എഡ്ജ് കമ്പ്യൂട്ടർ വിഷൻ: ആന്തരിക വിള്ളലുകൾ, തുരുമ്പ്, കേടുപാടുകൾ എന്നിവ തത്സമയം കണ്ടെത്തുന്നു.\n• സിലിണ്ടർ ഡ്രൈവ് ചേസിസ്: പൈപ്പുകൾക്കുള്ളിലൂടെ കൃത്യമായി സഞ്ചരിക്കാൻ സഹായിക്കുന്ന സംവിധാനം.\n• ലൈവ് ടെലിമെട്രി: ലൈവ് വീഡിയോയും പരിശോധനാ വിവരങ്ങളും കൺട്രോൾ ഡാഷ്‌ബോർഡിലേക്ക് അയയ്ക്കുന്നു.\n• സാങ്കേതികവിദ്യ: Python, OpenCV, എംബഡഡ് സിസ്റ്റംസ്, IoT എന്നിവ ഉപയോഗിച്ച് നിർമ്മിച്ചത്.',
    },
    keywords: {
      en: [
        'pipeline',
        'robot',
        'pipeline robot',
        'inspection robot',
        'robotics',
        'computer vision',
        'cv',
        'opencv',
        'crack detection',
        'pipe',
        'hardware project',
        'camera robot',
      ],
      ta: [
        'பைப்லைன்',
        'ரோபோ',
        'பைப்லைன் ரோபோ',
        'ஆய்வு ரோபோ',
        'ரோபோடிக்ஸ்',
        'கணினி பார்வை',
        'விரிசல் கண்டறிதல்',
        'குழாய் ரோபோ',
      ],
      hi: [
        'पाइपलाइन',
        'रोबोट',
        'पाइपलाइन रोबोट',
        'इंस्पेक्शन रोबोट',
        'कंप्यूटर विज़न',
        'रोबोटिक्स',
        'दरार पहचान',
      ],
      ml: [
        'പൈപ്പ്‌ലൈൻ',
        'റോബോട്ട്',
        'ഇൻസ്പെക്ഷൻ റോബോട്ട്',
        'റോബോട്ടിക്സ്',
        'കമ്പ്യൂട്ടർ വിഷൻ',
        'വിള്ളൽ പരിശോധന',
      ],
    },
    action: {
      label: {
        en: 'Inspect in My Work',
        ta: 'படைப்புகள் பக்கத்தில் காண்க',
        hi: 'प्रोजेक्ट्स पेज पर देखें',
        ml: 'പ്രോജക്റ്റുകളിൽ പരിശോധിക്കുക',
      },
      url: '/projects',
    },
    followUps: {
      en: ['What other projects have you built?', 'What technologies do you use?', 'How to hire Harsha?'],
      ta: ['வேறு என்ன திட்டங்கள் செய்துள்ளீர்கள்?', 'என்ன தொழில்நுட்பங்கள் பயன்படுத்துகிறீர்கள்?', 'ஹர்ஷாவை எவ்வாறு தொடர்பு கொள்வது?'],
      hi: ['अन्य कौन से प्रोजेक्ट्स बनाए हैं?', 'आप कौन सी तकनीक का उपयोग करते हैं?', 'हर्षा को कैसे हायर करें?'],
      ml: ['മറ്റ് ഏതൊക്കെ പ്രോജക്റ്റുകൾ ചെയ്തിട്ടുണ്ട്?', 'എന്തൊക്കെ സാങ്കേതികവിദ്യകൾ ഉപയോഗിക്കുന്നു?', 'ഹർഷയെ എങ്ങനെ ബന്ധപ്പെടാം?'],
    },
  },

  // 4. OTHER PROJECTS
  {
    id: 'projects',
    category: 'projects',
    answer: {
      en: 'Harsha’s portfolio includes three primary technical showcases:\n\n1. Pipeline Inspection Robot: Hardware/software robotics inspection prototype featuring edge computer vision and defect detection.\n2. Intelligent AI Workflow Automation: Multi-service LLM pipeline orchestrating webhooks, task queues, and context synthesis.\n3. Modern Full-Stack Platform: End-to-end type-safe web architecture with Next.js, TypeScript, PostgreSQL, and real-time synchronization.',
      ta: 'ஹர்ஷாவின் போர்ட்ஃபோலியோவில் உள்ள 3 முக்கிய தொழில்நுட்ப திட்டங்கள்:\n\n1. பைப்லைன் ஆய்வு ரோபோ: கணினி பார்வை மற்றும் எட்ஜ் AI மூலம் இயங்கும் ஆய்வு ரோபோ.\n2. நுண்ணறிவு AI பணி ஆட்டோமேஷன்: LLM மற்றும் வெப்ஹூக் ஒருங்கிணைப்புடன் கூடிய ஆட்டோமேஷன் பைப்லைன்.\n3. நவீன ஃபுல்-ஸ்டாக் தளம்: Next.js, TypeScript, PostgreSQL கொண்ட உயர் செயல்திறன் கொண்ட வலைப்பயன்பாடு.',
      hi: 'हर्षा के पोर्टफोलियो में 3 मुख्य प्रोजेक्ट्स शामिल हैं:\n\n1. पाइपलाइन इंस्पेक्शन रोबोट: कंप्यूटर विज़न और एज AI आधारित रोबोटिक निरीक्षण प्रणाली।\n2. इंटेलिजेंट AI वर्कफ़्लो ऑटोमेशन: मल्टी-सर्विस LLM पाइपलाइन और टास्क ऑटोमेशन।\n3. मॉडर्न फुल-स्टैक वेब प्लेटफॉर्म: Next.js, TypeScript और PostgreSQL पर आधारित आधुनिक प्लेटफॉर्म।',
      ml: 'ഹർഷയുടെ പ്രധാനപ്പെട്ട 3 സാങ്കേതിക പ്രോജക്റ്റുകൾ:\n\n1. പൈപ്പ്‌ലൈൻ ഇൻസ്പെക്ഷൻ റോബോട്ട്: കമ്പ്യൂട്ടർ വിഷൻ അടിസ്ഥാനമാക്കിയുള്ള റോബോട്ടിക്സ് ഇൻസ്പെക്ഷൻ സിസ്റ്റം.\n2. ഇന്റലിജന്റ് AI വർക്ക്‌ഫ്ലോ ഓട്ടോമേഷൻ: LLM, വെബ്‌ഹുക്കുകൾ എന്നിവ സംയോജിപ്പിച്ച ഓട്ടോമേഷൻ പൈപ്പ്‌ലൈൻ.\n3. മോഡേൺ ഫുൾ-സ്റ്റാക്ക് പ്ലാറ്റ്‌ഫോം: Next.js, TypeScript, PostgreSQL എന്നിവ ഉപയോഗിച്ചുള്ള ആധുനിക വെബ് പ്ലാറ്റ്‌ഫോം.',
    },
    keywords: {
      en: [
        'projects',
        'project',
        'portfolio',
        'my work',
        'case studies',
        'past work',
        'work sample',
        'what have you built',
        'github projects',
      ],
      ta: [
        'திட்டங்கள்',
        'படைப்புகள்',
        'போர்ட்ஃபோலியோ',
        'முந்தைய வேலைகள்',
        'மாதிரிகள்',
        'நீங்கள் உருவாக்கியவை',
      ],
      hi: [
        'प्रोजेक्ट्स',
        'पोर्टफोलियो',
        'काम के नमूने',
        'पिछला काम',
        'आपने क्या बनाया है',
      ],
      ml: [
        'പ്രോജക്റ്റുകൾ',
        'പോർട്ട്‌ഫോളിയോ',
        'മുൻകാല വർക്കുകൾ',
        'എന്താണ് നിർമ്മിച്ചിട്ടുള്ളത്',
      ],
    },
    action: {
      label: {
        en: 'View All Projects',
        ta: 'அனைத்து திட்டங்களையும் காண்க',
        hi: 'सभी प्रोजेक्ट्स देखें',
        ml: 'എല്ലാ പ്രോജക്റ്റുകളും കാണുക',
      },
      url: '/projects',
    },
    followUps: {
      en: ['Tell me about the Pipeline Robot', 'What tech stack do you use?', 'How much do you charge?'],
      ta: ['பைப்லைன் ரோபோ பற்றி சொல்லுங்கள்', 'என்ன தொழில்நுட்பங்கள் பயன்படுத்துகிறீர்கள்?', 'கட்டணம் எவ்வளவு?'],
      hi: ['पाइपलाइन रोबोट के बारे में बताएं', 'आप कौन सी तकनीक प्रयोग करते हैं?', 'फीस कितनी है?'],
      ml: ['പൈപ്പ്‌ലൈൻ റോബോട്ടിനെക്കുറിച്ച് പറയൂ', 'ഏതൊക്കെ ടൂളുകൾ ഉപയോഗിക്കുന്നു?', 'എത്ര ചെലവാകും?'],
    },
  },

  // 5. SKILLS & TECH STACK
  {
    id: 'skills',
    category: 'skills',
    answer: {
      en: 'Harsha’s engineering skill set includes:\n\n• Core Languages: TypeScript, JavaScript, Python, SQL, HTML5, CSS3\n• Frameworks & Libraries: Next.js (App Router), React, Tailwind CSS, Three.js, Node.js, Fastify, Express, OpenCV\n• Databases & Infrastructure: PostgreSQL, SQLite, REST APIs, WebSockets, Git\n• Architectural Strengths: Responsive layouts, accessibility (a11y), clean code, dark obsidian UI aesthetics, and multi-language architectures.',
      ta: 'ஹர்ஷாவின் தொழில்நுட்பத் திறன்கள்:\n\n• மொழிகள்: TypeScript, JavaScript, Python, SQL, HTML5, CSS3\n• கட்டமைப்புகள்: Next.js, React, Tailwind CSS, Three.js, Node.js, Fastify, Express, OpenCV\n• தரவுத்தளங்கள் & கருவிகள்: PostgreSQL, SQLite, REST APIs, WebSockets, Git\n• முக்கிய பலங்கள்: உயர் செயல்திறன், ரெஸ்பான்சிவ் வடிவமைப்பு, பயனர் அணுகல்தன்மை (a11y), மற்றும் பலமொழி கட்டமைப்பு.',
      hi: 'हर्षा की तकनीकी दक्षता:\n\n• भाषाएं: TypeScript, JavaScript, Python, SQL, HTML5, CSS3\n• फ्रेमवर्क्स और टूल्स: Next.js, React, Tailwind CSS, Three.js, Node.js, Fastify, OpenCV\n• डेटाबेस और इंफ्रास्ट्रक्चर: PostgreSQL, SQLite, REST APIs, WebSockets, Git\n• मुख्य विशेषताएं: सुपरफास्ट परफॉर्मेंस, रिस्पॉन्सिव डिज़ाइन, स्वच्छ कोड और डार्क थीम यूआई।',
      ml: 'ഹർഷയുടെ സാങ്കേതിക വൈദഗ്ധ്യങ്ങൾ:\n\n• പ്രോഗ്രാമിംഗ് ലാംഗ്വേജുകൾ: TypeScript, JavaScript, Python, SQL, HTML5, CSS3\n• ഫ്രെയിംവർക്കുകൾ: Next.js, React, Tailwind CSS, Three.js, Node.js, Fastify, OpenCV\n• ഡാറ്റാബേസുകൾ: PostgreSQL, SQLite, REST APIs, WebSockets, Git\n• പ്രധാന സവിശേഷതകൾ: മികച്ച പെർഫോമൻസ്, റെസ്പോൺസീവ് ഡിസൈൻ, പ്രീമിയം ഒബ്‌സിഡിയൻ ഡാർക്ക് തീം.',
    },
    keywords: {
      en: [
        'skills',
        'tech stack',
        'technologies',
        'stack',
        'tools',
        'languages',
        'python',
        'typescript',
        'javascript',
        'nextjs',
        'react',
        'tailwind',
        'threejs',
        'three.js',
        'node',
        'fastify',
        'opencv',
        'sql',
        'postgresql',
      ],
      ta: [
        'திறன்கள்',
        'தொழில்நுட்பங்கள்',
        'மொழிகள்',
        'டூல்ஸ்',
        'பைதான்',
        'டைப்ஸ்கிரிப்ட்',
        'ரியாக்ட்',
        'நெக்ஸ்ட்',
      ],
      hi: [
        'स्किल्स',
        'तकनीक',
        'टेक स्टैक',
        'टूल्स',
        'भाषाएं',
        'पायथन',
        'रिएक्ट',
        'नेक्स्ट जेएस',
      ],
      ml: [
        'സ്കിൽസ്',
        'സാങ്കേതികവിദ്യകൾ',
        'ടൂളുകൾ',
        'ഭാഷകൾ',
        'പൈത്തൺ',
        'റിയാക്റ്റ്',
      ],
    },
    action: {
      label: {
        en: 'View Services & Deliverables',
        ta: 'சேவைகளைக் காண்க',
        hi: 'सेवाएं देखें',
        ml: 'സേവനങ്ങൾ കാണുക',
      },
      url: '/services',
    },
    followUps: {
      en: ['What services do you offer?', 'Tell me about the Pipeline Robot', 'How to contact Harsha?'],
      ta: ['என்ன சேவைகள் வழங்குகிறீர்கள்?', 'பைப்லைன் ரோபோ பற்றி சொல்லுங்கள்', 'ஹர்ஷாவை எவ்வாறு தொடர்பு கொள்வது?'],
      hi: ['आप क्या सेवाएं देते हैं?', 'पाइपलाइन रोबोट के बारे में बताएं', 'हर्षा से संपर्क कैसे करें?'],
      ml: ['എന്തൊക്കെ സേവനങ്ങൾ നൽകുന്നു?', 'പൈപ്പ്‌ലൈൻ റോബോട്ടിനെക്കുറിച്ച് പറയൂ', 'ഹർഷയുമായി എങ്ങനെ ബന്ധപ്പെടാം?'],
    },
  },

  // 6. PRICING & BUDGET
  {
    id: 'pricing',
    category: 'pricing',
    answer: {
      en: 'Harsha’s core pricing philosophy is: “Big dreams shouldn\'t have to wait for big budgets.”\n\n• Transparent & Affordable: You pay only for what you need—without inflated agency overhead or surprise charges.\n• Custom Scoping: Every project is individually estimated based on clear requirements, complexity, and timelines.\n• Milestone Delivery: Payments can be split into milestones tied to verifiable progress demos.',
      ta: 'ஹர்ஷாவின் கட்டணக் கொள்கை: “பெரிய கனவுகளுக்கு பெரிய பட்ஜெட் தேவையில்லை.”\n\n• வெளிப்படையானது & நியாயமானது: அதிகப்படியான ஏஜென்சி செலவுகள் இல்லாமல், உங்கள் திட்டத்தின் தேவைகளுக்கு மட்டுமே கட்டணம்.\n• தனிப்பயன் மதிப்பீடு: திட்டத்தின் தன்மை மற்றும் காலக்கெடுவைப் பொறுத்து துல்லியமாக விலை நிர்ணயிக்கப்படுகிறது.\n• கட்ட வாரியான கட்டணம்: வேலை முன்னேற்றத்திற்கு ஏற்ப தவணை முறையில் கட்டணம் செலுத்தலாம்.',
      hi: 'हर्षा की फीस का मुख्य सिद्धांत है: "बड़े सपनों के लिए बड़े बजट की ज़रूरत नहीं होती।"\n\n• पारदर्शी और किफायती: बिना किसी छिपे हुए खर्च या एजेंसी मार्कअप के केवल आवश्यक काम के लिए भुगतान।\n• अनुकूलित कोटेशन: प्रत्येक प्रोजेक्ट की आवश्यकता और जटिलता के आधार पर उचित मूल्य तय किया जाता है।\n• माइलस्टोन भुगतान: कार्य की प्रगति के अनुसार चरणों में भुगतान की सुविधा।',
      ml: 'ഹർഷയുടെ ഫീസ് തത്വം: "വലിയ സ്വപ്നങ്ങൾക്ക് വലിയ ബജറ്റ് ആവശ്യമില്ല."\n\n• സുതാര്യവും താങ്ങാനാവുന്നതും: അനാവശ്യ ഏജൻസി ചെലവുകളില്ലാതെ കൃത്യമായ ആവശ്യങ്ങൾക്ക് മാത്രം പണം നൽകുക.\n• കസ്റ്റം എസ്റ്റിമേറ്റ്: ഓരോ പ്രോജക്റ്റിന്റെയും വ്യാപ്തി അനുസരിച്ച് മുൻകൂട്ടി ചെലവ് നിശ്ചയിക്കുന്നു.\n• ഘട്ടംഘട്ടമായുള്ള പേയ്‌മെന്റ്: പുരോഗതിക്കനുസരിച്ച് തവണകളായി പണം നൽകാം.',
    },
    keywords: {
      en: [
        'pricing',
        'price',
        'cost',
        'charge',
        'rate',
        'rates',
        'fee',
        'fees',
        'budget',
        'how much',
        'affordable',
        'quotation',
        'quote',
        'estimate',
      ],
      ta: [
        'விலை',
        'கட்டணம்',
        'எவ்வளவு ஆகும்',
        'பட்ஜெட்',
        'செலவு',
        'விலைப்பட்டியல்',
        'பணம்',
      ],
      hi: [
        'कीमत',
        'फीस',
        'खर्च',
        'बजट',
        'कितना चार्ज करते हैं',
        'दर',
        'कोटेशन',
      ],
      ml: [
        'വില',
        'ചെലവ്',
        'ചെലവാകും',
        'എത്ര ചെലവാകും',
        'ഫീസ്',
        'ബജറ്റ്',
        'എത്രയാകും',
        'നിരക്ക്',
      ],
    },
    action: {
      label: {
        en: 'Discuss Your Budget on Contact Page',
        ta: 'தொடர்பு பக்கத்தில் பேசலாம்',
        hi: 'कॉन्टैक्ट पेज पर चर्चा करें',
        ml: 'ബന്ധപ്പെടാനുള്ള പേജിൽ ചർച്ച ചെയ്യുക',
      },
      url: '/contact',
    },
    followUps: {
      en: ['How can I contact Harsha?', 'What is your turnaround time?', 'What services do you offer?'],
      ta: ['ஹர்ஷாவை எவ்வாறு தொடர்பு கொள்வது?', 'திட்டத்தை முடிக்க எவ்வளவு காலம் ஆகும்?', 'என்ன சேவைகள் வழங்குகிறீர்கள்?'],
      hi: ['हर्षा से संपर्क कैसे करें?', 'प्रोजेक्ट पूरा होने में कितना समय लगता है?', 'आप क्या सेवाएं देते हैं?'],
      ml: ['ഹർഷയുമായി എങ്ങനെ ബന്ധപ്പെടാം?', 'പ്രോജക്റ്റ് തീർക്കാൻ എത്ര സമയമെടുക്കും?', 'എന്തൊക്കെ സേവനങ്ങൾ നൽകുന്നു?'],
    },
  },

  // 7. CONTACT & CHANNELS
  {
    id: 'contact',
    category: 'contact',
    answer: {
      en: 'You can reach Harsha directly through any of the following channels:\n\n• WhatsApp: +91 6385386500 (Fastest response)\n• Direct Phone: +91 6385386500\n• Email: harshavardhan1527@gmail.com\n• GitHub: github.com/harshalancer\n• Contact Form: Visit the /contact page for guided enquiry formatting.\n\nHarsha is actively open to discussing new freelance projects and consultations.',
      ta: 'ஹர்ஷாவை நீங்கள் பின்வரும் வழிகளில் நேரடியாகத் தொடர்பு கொள்ளலாம்:\n\n• வாட்ஸ்அப்: +91 6385386500 (விரைவான பதில்)\n• தொலைபேசி: +91 6385386500\n• மின்னஞ்சல்: harshavardhan1527@gmail.com\n• GitHub: github.com/harshalancer\n• படிவம்: /contact பக்கத்தில் விவரங்களைப் பதிவு செய்யலாம்.\n\nபுதிய திட்டங்கள் மற்றும் ஆலோசனைகளுக்கு ஹர்ஷா எப்போதும் தயாராக உள்ளார்.',
      hi: 'आप हर्षा से सीधे इन माध्यमों से संपर्क कर सकते हैं:\n\n• व्हाट्सएप: +91 6385386500 (सबसे त्वरित उत्तर)\n• फ़ोन: +91 6385386500\n• ईमेल: harshavardhan1527@gmail.com\n• GitHub: github.com/harshalancer\n• संपर्क फ़ॉर्म: /contact पेज पर जाकर सीधे संदेश भेजें।\n\nहर्षा वर्तमान में नए फ्रीलांस प्रोजेक्ट्स के लिए उपलब्ध हैं।',
      ml: 'താഴെ പറയുന്ന വഴികളിലൂടെ നിങ്ങൾക്ക് ഹർഷയെ നേരിട്ട് ബന്ധപ്പെടാം:\n\n• വാട്ട്‌സ്ആപ്പ്: +91 6385386500 (വേഗത്തിൽ മറുപടി ലഭിക്കും)\n• ഫോൺ: +91 6385386500\n• ഇമെയിൽ: harshavardhan1527@gmail.com\n• GitHub: github.com/harshalancer\n• കോൺടാക്റ്റ് ഫോം: /contact പേജ് സന്ദർശിക്കുക.\n\nപുതിയ പ്രോജക്റ്റുകൾ ചർച്ച ചെയ്യാൻ ഹർഷ എപ്പോഴും സ്വാഗതം ചെയ്യുന്നു.',
    },
    keywords: {
      en: [
        'contact',
        'reach',
        'hire',
        'whatsapp',
        'phone',
        'email',
        'call',
        'number',
        'message',
        'talk',
        'chat with harsha',
        'get in touch',
        'availability',
      ],
      ta: [
        'தொடர்பு',
        'வாட்ஸ்அப்',
        'தொலைபேசி',
        'மின்னஞ்சல்',
        'பேச வேண்டும்',
        'தொடர்பு கொள்ள',
        'எண்',
      ],
      hi: [
        'संपर्क',
        'व्हाट्सएप',
        'फोन नंबर',
        'ईमेल',
        'कॉल',
        'मैसेज',
        'बात करनी है',
        'हायर',
      ],
      ml: [
        'ബന്ധപ്പെടുക',
        'ബന്ധപ്പെടാം',
        'എങ്ങനെ ബന്ധപ്പെടാം',
        'വാട്ട്‌സ്ആപ്പ്',
        'ഫോൺ നമ്പർ',
        'ഇമെയിൽ',
        'മെസ്സേജ്',
        'വിളിക്കുക',
      ],
    },
    action: {
      label: {
        en: 'Open WhatsApp Chat',
        ta: 'வாட்ஸ்அப் மூலம் பேசவும்',
        hi: 'व्हाट्सएप पर चैट करें',
        ml: 'വാട്ട്‌സ്ആപ്പിൽ സംസാരിക്കുക',
      },
      url: 'https://wa.me/916385386500?text=Hi%20Harsha%2C%20I%20visited%20your%20website%20and%20would%20like%20to%20discuss%20a%20project.',
      isExternal: true,
    },
    followUps: {
      en: ['Go to Contact Page', 'What services do you offer?', 'Tell me about your projects'],
      ta: ['தொடர்பு பக்கத்திற்குச் செல்லவும்', 'என்ன சேவைகள் வழங்குகிறீர்கள்?', 'திட்டங்கள் பற்றி சொல்லுங்கள்'],
      hi: ['कॉन्टैक्ट पेज पर जाएं', 'आप क्या सेवाएं देते हैं?', 'प्रोजेक्ट्स के बारे में बताएं'],
      ml: ['കോൺടാക്റ്റ് പേജിലേക്ക് പോകുക', 'എന്തൊക്കെ സേവനങ്ങൾ നൽകുന്നു?', 'പ്രോജക്റ്റുകളെക്കുറിച്ച് പറയൂ'],
    },
  },

  // 8. WORKFLOW & TURNAROUND
  {
    id: 'workflow',
    category: 'workflow',
    answer: {
      en: 'Harsha’s structured collaboration process:\n\n1. Scoping Discussion: Clarifying exact needs, features, timeline, and budget.\n2. Transparent Proposal: Written milestones and deliverables.\n3. Iterative Build: Regular live previews and checkpoints for your feedback.\n4. Quality Audit & Delivery: Performance, responsive QA, deployment, and smooth handover.',
      ta: 'ஹர்ஷாவின் திட்ட பணிமுறை:\n\n1. தேவைகளை அறிதல்: திட்டத்தின் முக்கிய தேவைகள், பட்ஜெட் மற்றும் காலக்கெடுவை உறுதி செய்தல்.\n2. தெளிவான திட்டம்: மைல்கற்கள் மற்றும் வழங்கப்பட வேண்டிய விவரங்கள்.\n3. கட்டமைப்பு & முன்னேற்றம்: உங்கள் கருத்துக்களைப் பெற்று தொடர்ச்சியான நேரலை மாதிரி பகிர்வு.\n4. தணிக்கை & ஒப்படைப்பு: முழுமையான சோதனை, இயக்கம் மற்றும் ஒப்படைப்பு.',
      hi: 'हर्षा की कार्य प्रक्रिया:\n\n1. आवश्यकता समझना: प्रोजेक्ट की ज़रूरतों, बजट और समयसीमा पर स्पष्ट चर्चा।\n2. स्पष्ट प्रस्ताव: माइलस्टोन और डिलीवरी की रूपरेखा।\n3. विकास और अपडेट: नियमित लाइव प्रोग्रेस अपडेट और आपका फीडबैक।\n4. परीक्षण और डिलीवरी: रिस्पॉन्सिव टेस्टिंग, स्पीड चेक और फाइनल हैंडओवर।',
      ml: 'ഹർഷയുടെ പ്രോജക്റ്റ് രീതി:\n\n1. ആവശ്യങ്ങൾ മനസ്സിലാക്കൽ: ബജറ്റ്, സമയപരിധി എന്നിവയെക്കുറിച്ചുള്ള വ്യക്തമായ ചർച്ച.\n2. പ്രൊപ്പോസൽ: കൃത്യമായ പ്ലാനും ഘട്ടങ്ങളും.\n3. നിർമ്മാണ പുരോഗതി: പതിവായി പുരോഗതി പങ്കുവെക്കുകയും ഫീഡ്‌ബാക്ക് എടുക്കുകയും ചെയ്യുക.\n4. ടെസ്റ്റിംഗ് & ഹാൻഡ്ഓവർ: കൃത്യമായ പരിശോധനയ്ക്ക് ശേഷം പൂർത്തിയാക്കൽ.',
    },
    keywords: {
      en: [
        'process',
        'workflow',
        'how do you work',
        'how it works',
        'steps',
        'timeline',
        'turnaround',
        'how long',
        'delivery time',
      ],
      ta: [
        'செயல்முறை',
        'பணிமுறை',
        'எவ்வாறு வேலை செய்கிறீர்கள்',
        'காலக்கெடு',
        'எவ்வளவு நாட்கள்',
      ],
      hi: [
        'प्रक्रिया',
        'वर्कफ़्लो',
        'आप कैसे काम करते हैं',
        'समयसीमा',
        'कितना समय लगेगा',
      ],
      ml: [
        'പ്രക്രിയ',
        'എങ്ങനെയാണ് ജോലി ചെയ്യുന്നത്',
        'സമയപരിധി',
        'എത്ര ദിവസം എടുക്കും',
      ],
    },
    action: {
      label: {
        en: 'Initiate a Project',
        ta: 'திட்டத்தைத் தொடங்கவும்',
        hi: 'प्रोजेक्ट शुरू करें',
        ml: 'പ്രോജക്റ്റ് ആരംഭിക്കുക',
      },
      url: '/contact',
    },
    followUps: {
      en: ['How much does a project cost?', 'What services do you offer?', 'How to contact Harsha?'],
      ta: ['விலை எவ்வளவு ஆகும்?', 'என்ன சேவைகள் வழங்குகிறீர்கள்?', 'ஹர்ஷாவைத் தொடர்பு கொள்வது எப்படி?'],
      hi: ['प्रोजेक्ट की फीस कितनी है?', 'आप क्या सेवाएं देते हैं?', 'हर्षा से संपर्क कैसे करें?'],
      ml: ['എത്ര ചെലവാകും?', 'എന്തൊക്കെ സേവനങ്ങൾ നൽകുന്നു?', 'ഹർഷയുമായി എങ്ങനെ ബന്ധപ്പെടാം?'],
    },
  },

  // 9. GREETING
  {
    id: 'greeting',
    category: 'about',
    answer: {
      en: 'Hello! I am Harsha’s Interactive Portfolio Assistant. I can answer questions about Harsha’s software services, tech skills, featured projects (like the Pipeline Inspection Robot), pricing philosophy, and how to get in touch.',
      ta: 'வணக்கம்! நான் ஹர்ஷாவின் போர்ட்ஃபோலியோ உதவியாளர். ஹர்ஷாவின் மென்பொருள் சேவைகள், தொழில்நுட்பத் திறன்கள், படைப்புகள் (பைப்லைன் ரோபோ போன்றவை), கட்டண விவரங்கள் மற்றும் தொடர்பு வழிகள் பற்றி என்னிடம் கேட்கலாம்.',
      hi: 'नमस्ते! मैं हर्षा का इंटरैक्टिव पोर्टफोलियो असिस्टेंट हूँ। मैं हर्षा की सॉफ्टवेयर सेवाओं, स्किल्स, प्रोजेक्ट्स (जैसे पाइपलाइन रोबोट), फीस और संपर्क से जुड़े सवालों के जवाब दे सकता हूँ।',
      ml: 'നമസ്കാരം! ഞാൻ ഹർഷയുടെ പോർട്ട്‌ഫോളിയോ അസിസ്റ്റന്റാണ്. ഹർഷയുടെ സോഫ്റ്റ്‌വെയർ സേവനങ്ങൾ, സാങ്കേതിക വിദ്യകൾ, പ്രോജക്റ്റുകൾ (പൈപ്പ്‌ലൈൻ റോബോട്ട് ഉൾപ്പെടെ), ഫീസ്, ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ എന്നിവയെക്കുറിച്ച് ഞാൻ സഹായിക്കാം.',
    },
    keywords: {
      en: [
        'hello',
        'hi',
        'hey',
        'good morning',
        'good evening',
        'good afternoon',
        'greetings',
        'start',
      ],
      ta: [
        'வணக்கம்',
        'ஹலோ',
        'ஹாய்',
        'நல்வரவு',
      ],
      hi: [
        'नमस्ते',
        'नमस्कार',
        'हेलो',
        'हाय',
      ],
      ml: [
        'നമസ്കാരം',
        'ഹലോ',
        'ഹായ്',
      ],
    },
    followUps: {
      en: ['What services do you offer?', 'Tell me about the Pipeline Robot', 'How to contact Harsha?'],
      ta: ['என்ன சேவைகள் வழங்குகிறீர்கள்?', 'பைப்லைன் ரோபோ பற்றி சொல்லுங்கள்', 'ஹர்ஷாவை எவ்வாறு தொடர்பு கொள்வது?'],
      hi: ['आप क्या सेवाएं देते हैं?', 'पाइपलाइन रोबोट के बारे में बताएं', 'हर्षा से संपर्क कैसे करें?'],
      ml: ['എന്തൊക്കെ സേവനങ്ങൾ നൽകുന്നു?', 'പൈപ്പ്‌ലൈൻ റോബോട്ടിനെക്കുറിച്ച് പറയൂ', 'ഹർഷയുമായി എങ്ങനെ ബന്ധപ്പെടാം?'],
    },
  },
];

// Fallback response when no intent matches
export const FALLBACK_RESPONSES: Record<SupportedLanguage, string> = {
  en: 'I specialize in answering questions about Harsha’s real services, skills, projects (such as the Pipeline Inspection Robot), pricing philosophy, and direct contact info. For custom enquiries or questions not covered here, feel free to contact Harsha directly!',
  ta: 'ஹர்ஷாவின் உண்மையான சேவைகள், திறன்கள், திட்டங்கள் (பைப்லைன் ஆய்வு ரோபோ போன்றவை), மற்றும் தொடர்பு விவரங்கள் குறித்த கேள்விகளுக்கு என்னால் பதிலளிக்க முடியும். தனிப்பயன் திட்ட ஆலோசனைக்கு ஹர்ஷாவை நேரடியாக தொடர்பு கொள்ளலாம்!',
  hi: 'मैं हर्षा की वास्तविक सेवाओं, स्किल्स, प्रोजेक्ट्स (जैसे पाइपलाइन इंस्पेक्शन रोबोट), फीस और संपर्क संबंधी सवालों में मदद कर सकता हूँ। किसी विशेष जानकारी के लिए आप सीधे हर्षा से संपर्क कर सकते हैं!',
  ml: 'ഹർഷയുടെ സേവനങ്ങൾ, പ്രോജക്റ്റുകൾ (പൈപ്പ്‌ലൈൻ ഇൻസ്പെക്ഷൻ റോബോട്ട് ഉൾപ്പെടെ), സാങ്കേതികവിദ്യകൾ, ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ എന്നിവയെക്കുറിച്ചുള്ള ചോദ്യങ്ങൾക്ക് എനിക്ക് മറുപടി നൽകാനാകും. കൂടുതൽ വിവരങ്ങൾക്ക് ഹർഷയുമായി നേരിട്ട് ബന്ധപ്പെടുക!',
};

// UI Translations for the Chatbot Widget
export interface ChatbotUiStrings {
  title: string;
  subtitle: string;
  placeholder: string;
  send: string;
  typing: string;
  clearChat: string;
  close: string;
  minimize: string;
  expand: string;
  starterPromptTitle: string;
  starters: string[];
  contactButton: string;
  disclaimer: string;
}

export const CHATBOT_UI: Record<SupportedLanguage, ChatbotUiStrings> = {
  en: {
    title: "Harsha's Assistant",
    subtitle: 'Local Knowledge Base • 100% Free & Private',
    placeholder: 'Ask about services, projects, skills, pricing...',
    send: 'Send',
    typing: 'Harsha Assistant is typing...',
    clearChat: 'Clear chat',
    close: 'Close chat',
    minimize: 'Minimize',
    expand: 'Open FAQ Assistant',
    starterPromptTitle: 'Suggested Questions:',
    starters: [
      'What services do you offer?',
      'Tell me about the Pipeline Robot',
      'What is your pricing philosophy?',
      'How can I contact Harsha?',
    ],
    contactButton: 'Go to Contact Page',
    disclaimer: 'Deterministic local FAQ assistant. Never invents facts.',
  },
  ta: {
    title: 'ஹர்ஷாவின் உதவியாளர்',
    subtitle: 'உள்ளமைவு அறிவுத் தளம் • இலவசம் & பாதுகாப்பானது',
    placeholder: 'சேவைகள், திட்டங்கள், திறன்கள், கட்டணம் பற்றி கேட்கவும்...',
    send: 'அனுப்பு',
    typing: 'பதிலளிக்கிறது...',
    clearChat: 'அரட்டையை அழிக்கவும்',
    close: 'அரட்டையை மூடவும்',
    minimize: 'சுருக்கவும்',
    expand: 'FAQ உதவியாளரைத் திறக்கவும்',
    starterPromptTitle: 'பரிந்துரைக்கப்பட்ட கேள்விகள்:',
    starters: [
      'என்ன சேவைகள் வழங்குகிறீர்கள்?',
      'பைப்லைன் ரோபோ பற்றி சொல்லுங்கள்',
      'கட்டணம் எவ்வளவு ஆகும்?',
      'ஹர்ஷாவை எவ்வாறு தொடர்பு கொள்வது?',
    ],
    contactButton: 'தொடர்பு பக்கத்திற்குச் செல்லவும்',
    disclaimer: 'உண்மையான தகவல்களை மட்டுமே வழங்கும் உள்ளமைவு உதவியாளர்.',
  },
  hi: {
    title: 'हर्षा का असिस्टेंट',
    subtitle: 'लोकल नॉलेज बेस • 100% फ्री और सुरक्षित',
    placeholder: 'सेवाएं, प्रोजेक्ट्स, स्किल्स, फीस के बारे में पूछें...',
    send: 'भेजें',
    typing: 'टाइप कर रहा है...',
    clearChat: 'चैट साफ़ करें',
    close: 'चैट बंद करें',
    minimize: 'छोटा करें',
    expand: 'FAQ असिस्टेंट खोलें',
    starterPromptTitle: 'सुझाए गए प्रश्न:',
    starters: [
      'आप क्या सेवाएं देते हैं?',
      'पाइपलाइन रोबोट के बारे में बताएं',
      'प्रोजेक्ट की फीस कितनी है?',
      'हर्षा से संपर्क कैसे करें?',
    ],
    contactButton: 'कॉन्टैक्ट पेज पर जाएं',
    disclaimer: 'सटीक व वास्तविक जानकारी पर आधारित लोकल FAQ असिस्टेंट।',
  },
  ml: {
    title: 'ഹർഷയുടെ അസിസ്റ്റന്റ്',
    subtitle: 'ലോക്കൽ നോളജ് ബേസ് • 100% സൗജന്യവും സുരക്ഷിതവും',
    placeholder: 'സേവനങ്ങൾ, പ്രോജക്റ്റുകൾ, സ്കിൽസ് എന്നിവ ചോദിക്കൂ...',
    send: 'അയക്കുക',
    typing: 'ടൈപ്പ് ചെയ്യുന്നു...',
    clearChat: 'ചാറ്റ് ക്ലിയർ ചെയ്യുക',
    close: 'ചാറ്റ് ക്ലോസ് ചെയ്യുക',
    minimize: 'ചെറുതാക്കുക',
    expand: 'FAQ അസിസ്റ്റന്റ് തുറക്കുക',
    starterPromptTitle: 'നിർദ്ദേശിച്ച ചോദ്യങ്ങൾ:',
    starters: [
      'എന്തൊക്കെ സേവനങ്ങൾ നൽകുന്നു?',
      'പൈപ്പ്‌ലൈൻ റോബോട്ടിനെക്കുറിച്ച് പറയൂ',
      'ഫീസ് എത്രയാകും?',
      'ഹർഷയുമായി എങ്ങനെ ബന്ധപ്പെടാം?',
    ],
    contactButton: 'കോൺടാക്റ്റ് പേജിലേക്ക് പോകുക',
    disclaimer: 'യാഥാർത്ഥ വിവരങ്ങൾ മാത്രം നൽകുന്ന ലോക്കൽ അസിസ്റ്റന്റ്.',
  },
};
